version: "3.8"

services:
  db:
    image: postgres:15
    container_name: testgen-db
    restart: always
    env_file:
      - ./server/.env.docker
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: testgen-backend
    restart: always
    env_file:
      - ./server/.env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/tests/1"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build: ./client
    container_name: testgen-frontend
    restart: always
    env_file:
      - ./client/.env.docker
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run preview -- --host"
    # Use "--host" to allow access from outside the container

volumes:
  db-data:
